### ISSUE TITLE
Supporting of rfc6902 specification for JSON type?

### ISSUE THREAD

**Issue by skotchio** [ottypes/json0#4]
Do you plan to create ottype for supporting of  JavaScript Object Notation (rfc6902 JSON) Patch specification?

**Comment by gaurav21r** [comment]
@josephg Absolutely great work on this project! I'm not asking for a *status* per se on `json1` :stuck_out_tongue: Just wanted to know if it is still in your plans. More importantly, since you were mentioning some work on object move, maybe you could release a public repo? I'm sure some of us can think to contribute once a repo is in place?

**Comment by josephg** [comment]
Yeah its in a public repo at [josephg/json1](https://github.com/josephg/json1)

I've been writing about the process on the sharejs mailing list - should we have a mailing list for JSON OT?

**Comment by gaurav21r** [comment]
@josephg Oops sorry my bad. I think it depends on volume of communication? I think ShareJS mailing list alone is also fine, but I think you need to communicates this in JSON OT `README.md`?

I'm all for an **ottypes** mailing list as well which can discuss `text0`, `json0` and `json1`

**Comment by josephg** [comment]
It took me a few years to get everything working, and its still not 100% ready. But the [new JSON1 type is here](https://www.npmjs.com/package/ot-json1). Now is the time to add JSON patch support if you want it - maybe [file an issue in the json1 repo](https://github.com/ottypes/json1) to get the ball rolling about json patch support if its still important to you
